sudo: required
services:
    - docker
#you can use the full path for tagging, or simply you can put a name instead of full path
before_install:
    - docker build -t willrocha92/docker-react -f Dockerfile.dev .
script:    
    - docker run -e CI=true willrocha92/docker-react npm run test
deploy:
    provider: elasticbeanstalk
    region:"us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-092345619251"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $aws-access-key
    secret_access_key: "$aws-secret-key"
